name: Package tf-tools version

on:
  release:
    types: [created]

jobs:
  package:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install VSCE
        run: npm install -g vsce

      - name: Install dependencies
        run: npm install

      - name: Package VS code extension
        run: vsce package

      - name: Upload extension file to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: tf-tools-${{ env.VERSION }}.vsix
          token: ${{ secrets.RELEASE_TOKEN }}
